const express = require('express');
const bodyParser = require('body-parser');
const app = express();
const Post = require('./models/post');
const mongoose = require('mongoose');

//mongoose.connect('mongodb://mongoadmin:secret@my_mongo:27017/test?retryWrites=true')
mongoose.connect('mongodb://meanuser:meanuser@my_mongo:27017/mean_course', {useNewUrlParser: true})
    .then(()=>{
        console.log('Connected to the DB');
    })
    .catch(()=>{
        console.log('Connection failed');
    });

app.use(bodyParser.json());
app.use(bodyParser.urlencoded({ extended: false})); //not used but nice-to-have

app.use((req, res, next) => {
    res.setHeader('Access-Control-Allow-Origin', '*');
    res.setHeader(
        'Access-Control-Allow-Headers', 
        'Origin, X-Requested-With, Content-Type, Accept');
    res.setHeader(
        'Access-Control-Allow-Methods',
        'GET, POST, PATCH, DELETE, PUT, OPTIONS'
    )
    next();
});

app.post("/api/posts", (req, res, next) => {
    const post = new Post(
        {
            title: req.body.title,
            content: req.body.content
        });
    console.log(post);
    post.save(); //save generated by post.js model which imported mongoose
    res.status(201).json({
        message: "Post added successfully"
    });
})


app.get('/api/posts',(req, res, next) => {
    Post.find()
        .then(documents => {
                console.log(documents);
                res.status(200).json({
                    message: 'Post fetched successfully',
                    posts: documents
                });
            }
        );
});

module.exports = app;